from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
)
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.lib.units import inch

import base64
from io import BytesIO
from PIL import Image as PILImage


def add_footer(canvas, doc):
    canvas.saveState()

    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.grey)

    footer_text = "Generated by AI | Chest X-ray Disease Detection System"
    canvas.drawString(40, 20, footer_text)

    page_number = f"Page {doc.page}"
    canvas.drawRightString(A4[0] - 40, 20, page_number)

    canvas.restoreState()


def base64_to_reportlab_image(base64_str, width=2.6 * inch, height=2.6 * inch):
    img_data = base64.b64decode(base64_str)
    pil_img = PILImage.open(BytesIO(img_data)).convert("RGB")

    img_buffer = BytesIO()
    pil_img.save(img_buffer, format="PNG")
    img_buffer.seek(0)

    return Image(img_buffer, width=width, height=height)


# ✅ OLD FORMAT PDF (IN-MEMORY VERSION)
def generate_pdf_bytes(patient_data, prediction_data):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=60,
        bottomMargin=50
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "titleStyle",
        parent=styles["Heading1"],
        alignment=TA_CENTER,
        textColor=colors.darkblue,
        fontSize=18,
        spaceAfter=8
    )

    subtitle_style = ParagraphStyle(
        "subtitleStyle",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        textColor=colors.grey,
        fontSize=11,
        spaceAfter=15
    )

    heading_style = ParagraphStyle(
        "headingStyle",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=colors.darkblue,
        spaceBefore=15,
        spaceAfter=8
    )

    normal_style = ParagraphStyle(
        "normalStyle",
        parent=styles["Normal"],
        fontSize=10.5,
        leading=14,
        alignment=TA_JUSTIFY
    )

    bullet_style = ParagraphStyle(
        "bulletStyle",
        parent=styles["Normal"],
        fontSize=10.5,
        leading=14,
        leftIndent=18
    )

    section_title_style = ParagraphStyle(
        "sectionTitleStyle",
        parent=styles["Heading3"],
        fontSize=12,
        textColor=colors.black,
        spaceBefore=10,
        spaceAfter=6
    )

    center_heading_style = ParagraphStyle(
        "centerHeadingStyle",
        parent=styles["Normal"],
        fontSize=11,
        leading=14,
        alignment=TA_CENTER,
        textColor=colors.black
    )

    story = []

    # HEADER
    story.append(Paragraph("CHEST X-RAY MEDICAL REPORT", title_style))
    story.append(Paragraph("AI Assisted Radiology Diagnostic Report", subtitle_style))

    # PATIENT DETAILS
    patient_table_data = [
        [
            Paragraph("<b>Patient Name:</b>", normal_style),
            Paragraph(str(patient_data.get("patient_name", "")), normal_style),
            Paragraph("<b>Age:</b>", normal_style),
            Paragraph(str(patient_data.get("patient_age", "")), normal_style),
        ],
        [
            Paragraph("<b>Gender:</b>", normal_style),
            Paragraph(str(patient_data.get("patient_gender", "")), normal_style),
            Paragraph("<b>Phone Number:</b>", normal_style),
            Paragraph(str(patient_data.get("patient_phone", "")), normal_style),
        ]
    ]

    patient_table = Table(patient_table_data, colWidths=[110, 160, 110, 90])

    patient_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.whitesmoke),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
        ("BOX", (0, 0), (-1, -1), 1, colors.grey),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))

    story.append(patient_table)
    story.append(Spacer(1, 12))

    # PREDICTION DETAILS
    info_table_data = [
        [
            Paragraph("<b>Date:</b>", normal_style),
            Paragraph(prediction_data.get("date_str", ""), normal_style),
            Paragraph("<b>Time:</b>", normal_style),
            Paragraph(prediction_data.get("time_str", ""), normal_style),
        ],
        [
            Paragraph("<b>Predicted Disease:</b>", normal_style),
            Paragraph(f"{prediction_data.get('disease', '')}", normal_style),
            Paragraph("<b>Confidence:</b>", normal_style),
            Paragraph(f"{prediction_data.get('confidence', '')}%", normal_style),
        ]
    ]

    info_table = Table(info_table_data, colWidths=[110, 160, 110, 90])

    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.whitesmoke),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
        ("BOX", (0, 0), (-1, -1), 1, colors.grey),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))

    story.append(info_table)
    story.append(Spacer(1, 18))

    # IMAGES SECTION
    story.append(Paragraph("Radiology Images", heading_style))

    disease = prediction_data.get("disease", "NORMAL")

    input_base64 = prediction_data.get("input_image")
    gradcam_base64 = prediction_data.get("gradcam_image")

    if disease == "NORMAL":
        uploaded_img = base64_to_reportlab_image(
            input_base64,
            width=4.8 * inch,
            height=4.8 * inch
        )

        image_table = Table(
            [
                [Paragraph("<b>Uploaded Chest X-ray</b>", center_heading_style)],
                [uploaded_img]
            ],
            colWidths=[6.0 * inch]
        )

        image_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BOX", (0, 0), (-1, -1), 1, colors.grey),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("PADDING", (0, 0), (-1, -1), 10),
        ]))

        story.append(image_table)
        story.append(Spacer(1, 20))

    else:
        uploaded_img_small = base64_to_reportlab_image(
            input_base64,
            width=2.6 * inch,
            height=2.6 * inch
        )

        gradcam_img = base64_to_reportlab_image(
            gradcam_base64,
            width=2.6 * inch,
            height=2.6 * inch
        )

        image_table = Table(
            [
                [
                    Paragraph("<b>Uploaded Chest X-ray</b>", center_heading_style),
                    Paragraph("<b>Grad-CAM Highlighted Region</b>", center_heading_style)
                ],
                [uploaded_img_small, gradcam_img]
            ],
            colWidths=[3.0 * inch, 3.0 * inch]
        )

        image_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BOX", (0, 0), (-1, -1), 1, colors.grey),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))

        story.append(image_table)
        story.append(Spacer(1, 20))

    # AI RESPONSE SECTION
    story.append(Paragraph("AI Medical Guidance", heading_style))

    ai_response = prediction_data.get("ai_response", "")
    lines = ai_response.split("\n")

    for line in lines:
        line = line.strip()
        if not line:
            continue

        upper_line = line.upper()

        # ✅ Replace SECTION headings with clean headings
        if "SUMMARY" in upper_line and "SECTION" in upper_line:
            story.append(Spacer(1, 8))
            story.append(Paragraph("<b>SUMMARY</b>", section_title_style))
            story.append(Spacer(1, 4))

        elif "COMMON SYMPTOMS" in upper_line and "SECTION" in upper_line:
            story.append(Spacer(1, 8))
            story.append(Paragraph("<b>COMMON SYMPTOMS</b>", section_title_style))
            story.append(Spacer(1, 4))

        elif "PRECAUTIONS" in upper_line and "SECTION" in upper_line:
            story.append(Spacer(1, 8))
            story.append(Paragraph("<b>PRECAUTIONS</b>", section_title_style))
            story.append(Spacer(1, 4))

        elif ("PREVENTION MEASURES" in upper_line or "PREVENTIONS" in upper_line) and "SECTION" in upper_line:
            story.append(Spacer(1, 8))
            story.append(Paragraph("<b>PREVENTIONS</b>", section_title_style))
            story.append(Spacer(1, 4))

        # ✅ NORMAL headings if AI sends them directly without SECTION
        elif upper_line == "SUMMARY":
            story.append(Spacer(1, 8))
            story.append(Paragraph("<b>SUMMARY</b>", section_title_style))
            story.append(Spacer(1, 4))

        elif upper_line == "COMMON SYMPTOMS":
            story.append(Spacer(1, 8))
            story.append(Paragraph("<b>COMMON SYMPTOMS</b>", section_title_style))
            story.append(Spacer(1, 4))

        elif upper_line == "PRECAUTIONS":
            story.append(Spacer(1, 8))
            story.append(Paragraph("<b>PRECAUTIONS</b>", section_title_style))
            story.append(Spacer(1, 4))

        elif upper_line == "PREVENTION MEASURES" or upper_line == "PREVENTIONS":
            story.append(Spacer(1, 8))
            story.append(Paragraph("<b>PREVENTIONS</b>", section_title_style))
            story.append(Spacer(1, 4))

        # ✅ Special case: NORMAL response headings "Precautions for ..."
        elif line.lower().startswith("precautions for"):
            story.append(Spacer(1, 8))
            story.append(Paragraph(f"<b>{line}</b>", section_title_style))
            story.append(Spacer(1, 4))

        # BULLETS
        elif line.startswith("-"):
            story.append(Paragraph(f"• {line[1:].strip()}", bullet_style))

        # NORMAL TEXT
        else:
            story.append(Paragraph(line, normal_style))

    # DISCLAIMER
    story.append(Spacer(1, 18))
    story.append(Paragraph(
        "<b>Disclaimer:</b> This report is generated using AI for educational and informational purposes. "
        "It is not a substitute for professional medical diagnosis. Please consult a certified doctor for final confirmation.",
        normal_style
    ))

    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)

    buffer.seek(0)
    return buffer.getvalue()
